<?php

namespace Techquity\Aero\Couriers\Services\FedEx\References;

class CurrencyCodes
{
    public const DEFAULT = 'UKL';
    public const CODES = [
        'Antilles Guilder' => 'ANG',
        'Argentinian Peso' => 'ARN',
        'Aruban Florijn' => 'AWG',
        'Australian Dollar' => 'AUD',
        'Bahamian Dollars' => 'BSD',
        'Bahraini Dinar' => 'BHD',
        'Barbados Dollar' => 'BBD',
        'Bermuda Dollar' => 'BMD',
        'Brazilian Real' => 'BRL',
        'Brunei Dollar' => 'BND',
        'Bulgarian lev' => 'BGN',
        'Canadian Dollar' => 'CAD',
        'Cayman Dollars' => 'CID',
        'Chilean Peso' => 'CHP',
        'Chinese Renminbi' => 'CNY',
        'Colombian Peso' => 'COP',
        'Costa Rican Colon' => 'CRC',
        'Croatian Kuna' => 'HRK',
        'Czech Republic Koruny' => 'CZK',
        'Danish Krone' => 'DKK',
        'Dominican Peso' => 'RDD',
        'E. Caribbean Dollar' => 'ECD',
        'Egyptian Pound' => 'EGP',
        'Euro' => 'EUR',
        'Guatemalan Quetzal' => 'GTQ',
        'Hong Kong Dollar' => 'HKD',
        'Hungarian Forint' => 'HUF',
        'Indian Rupee' => 'INR',
        'Indonesian Rupiah' => 'IDR',
        'Israeli Shekel' => 'ILS',
        'Jamaican Dollar' => 'JAD',
        'Japanese Yen' => 'JYE',
        'Kazachstan Tenge' => 'KZT',
        'Kenyan Schilling' => 'KES',
        'Kuwaiti Dinar' => 'KUD',
        'Latvian Lats, Lithuanian Litas' => 'EURO',
        'Libyan Dinar' => 'LYD',
        'Macau Patacas' => 'MOP',
        'Malaysian Ringgits' => 'MYR',
        'Mauritian Rupee' => 'MUR',
        'Mozambican Metical' => 'MZN',
        'New Mexican Peso' => 'NMP',
        'New Taiwan Dollar' => 'NTD',
        'New Turkish Lira' => 'TRY',
        'New Zealand Dollar' => 'NZD',
        'Norwegian Krone' => 'NOK',
        'Pakistan Rupee' => 'PKR',
        'Panama Balboa' => 'PAB',
        'Philippine Peso' => 'PHP',
        'Polish Zloty' => 'PLN',
        'Romanian Leu' => 'RON',
        'Russian Ruble' => 'RUB',
        'Saudi Arabian Riyal' => 'SAR',
        'Singapore Dollar' => 'SID',
        'Solomon Island Dollar' => 'SBD',
        'South African Rand' => 'ZAR',
        'South Korean Won' => 'WON',
        'Swedish Krona' => 'SEK',
        'Swiss Francs' => 'SFR',
        'Thailand Baht' => 'THB',
        'Tonga Pa\'anga' => 'TOP',
        'Trinidad & Tobago Dollar' => 'TTD',
        'Uganda Schilling' => 'UGX',
        'UK Pounds Sterling' => 'UKL',
        'United Arab Emirates Dirham' => 'DHS',
        'United States Dollar' => 'USD',
        'Uruguay New Peso' => 'UYP',
        'Venezuela Bolivar Fuerte' => 'VEF',
        'Vietnamese Dong' => 'VND',
        'Western Samoa Tala' => 'WST',
    ];
}
